Fix bashate warnings and remove obsolete scripts

diff --git a/compile_kernel b/compile_kernel
--- a/compile_kernel
+++ b/compile_kernel
@@ -4,21 +4,21 @@
 #
 
 if [ ! -r .config ] ; then
-	echo "You must be in the source directory of a configured kernel."
-	exit 1
+    echo "You must be in the source directory of a configured kernel."
+    exit 1
 fi
 
 VERSION=$(git log --oneline | head | cut -d' ' -f2,3 | grep "^Linux" | head -1 | cut -d' ' -f2)
 
 if [ "z$VERSION" = "z" ] ; then
-	echo "Could not extract kernel version from the git log."
-	exit 2;
+    echo "Could not extract kernel version from the git log."
+    exit 2;
 fi
 
 # Set the number of parallel runs of gcc
 export CONCURRENCY_LEVEL=$1
 if [ "z$1" = "z" ] ; then
-	export CONCURRENCY_LEVEL=3
+    export CONCURRENCY_LEVEL=3
 fi
 
 # Prime sudo for later
diff --git a/git-apply-grsec b/git-apply-grsec
--- a/git-apply-grsec
+++ b/git-apply-grsec
@@ -3,22 +3,22 @@
 # Apply a grsecurity patch over a kernel stored in git
 
 if [ "z$1" = "z" ] ; then
-	echo "Usage: $0 <grsecurity-version>.patch"
-	exit 1;
+    echo "Usage: $0 <grsecurity-version>.patch"
+    exit 1;
 elif [ ! -r "$1" ] ; then
-	echo "Cannot open file $1"
-	exit 2;
+    echo "Cannot open file $1"
+    exit 2;
 elif [ ! -r ".config" ] ; then
-	echo "You must run this script inside the source tree of a configured kernel."
-	exit 3;
+    echo "You must run this script inside the source tree of a configured kernel."
+    exit 3;
 fi
 
 # Remove the last patch if necessary
 NEEDS_RESET="$(git log --oneline | head -1 | grep 'Applied grsecurity' >/dev/null && echo yes)"
 if [ "z$NEEDS_RESET" = "zyes" ] ; then
-        git reset --hard HEAD^
-        git clean -f
-        git clean -d -f
+    git reset --hard HEAD^
+    git clean -f
+    git clean -d -f
 fi
 
 fakeroot make-kpkg clean
diff --git a/mkpodcast b/mkpodcast
--- a/mkpodcast
+++ b/mkpodcast
@@ -3,13 +3,13 @@
 # Used to extract and compress audio from video files
 
 if [ -e "audiodump.wav" ] ; then
-	echo "ERROR: audiodump already exists"
-	exit 1
+    echo "ERROR: audiodump already exists"
+    exit 1
 fi
 
 if [ ! -r "$1" ] ; then
-	echo "Usage: $0 file_to_dump"
-	exit 2
+    echo "Usage: $0 file_to_dump"
+    exit 2
 fi
 
 mplayer -msglevel all=0 -novideo -nocache -nobps -ni -forceidx -mc 0 -ao pcm:waveheader "$1"
