Abort when we failed to apply a patch cleanly

diff --git a/git-apply-grsec b/git-apply-grsec
--- a/git-apply-grsec
+++ b/git-apply-grsec
@@ -22,7 +22,7 @@ if [ "z$NEEDS_RESET" = "zyes" ] ; then
 fi
 
 fakeroot make-kpkg clean
-patch -p1 < $1
+(patch -p1 < $1) || (echo "Failed to apply patch" && exit 1)
 git add grsecurity/ include/linux/gr* localversion-grsec tools/
 git add include/linux/netfilter net/netfilter scripts/gcc-plugin.sh
 git commit -a -m "Applied `basename $1`"
